/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class helloworld_HelloWorld */

#ifndef _Included_helloworld_HelloWorld
#define _Included_helloworld_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     helloworld_HelloWorld
 * Method:    helloWorld_c
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_helloworld_HelloWorld_helloWorld_1c
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
